Started by user [8mha:AAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzREgZu/dLi1CL9nNSi7HwATSuZe8AAAAA=[0mLerko Araya Hernandez
Building in workspace /var/lib/jenkins/workspace/RaiseErrorTest
No emails were triggered.
[RaiseErrorTest] $ /bin/sh -xe /tmp/hudson3581166271779908382.sh
+ python -u /home/lerko/Desktop/Detector/RaiseErrorTest.py
Traceback (most recent call last):
  File "/home/lerko/Desktop/Detector/RaiseErrorTest.py", line 12, in <module>
    main()
  File "/home/lerko/Desktop/Detector/RaiseErrorTest.py", line 9, in main
    detection = myDetector.execute()
  File "/home/lerko/Desktop/Detector/DetectorsType1.py", line 61, in execute
    raise Exception('Error Raiser for ErrorRaiserDetector')
Exception: Error Raiser for ErrorRaiserDetector
Build step 'Run with timeout' marked build as failure
No emails were triggered.
Finished: FAILURE
