Started by user [8mha:AAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzREgZu/dLi1CL9nNSi7HwATSuZe8AAAAA=[0mLerko Araya Hernandez
Building in workspace /var/lib/jenkins/workspace/RaiseErrorTest
No emails were triggered.
[RaiseErrorTest] $ /bin/sh -xe /tmp/hudson6930585319670717854.sh
+ python -u /home/lerko/Desktop/Detector/RaiseError.py
python: can't open file '/home/lerko/Desktop/Detector/RaiseError.py': [Errno 2] No such file or directory
Build step 'Run with timeout' marked build as failure
No emails were triggered.
Finished: FAILURE
